schema_version = "1.0.0"

id = "io_scene_foundry"
version = "1.3.12"
name = "Foundry"
tagline = "An import & export pipeline for Halo Reach, Halo 4, and Halo 2 Anniversary Multiplayer"
maintainer = "Crisp"
type = "add-on"

permissions = ["files", "clipboard"]

website = "https://c20.reclaimers.net/general/community-tools/foundry/"

tags = ["Import-Export", "Pipeline"]

blender_version_min = "5.0.0"

license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-amd64", "windows-x64"]

wheels = [
  "./wheels/cffi-1.16.0-cp311-cp311-win_amd64.whl",
  "./wheels/clr_loader-0.2.7.post0-py3-none-any.whl",
  "./wheels/pycparser-2.22-py3-none-any.whl",
  "./wheels/pymem-1.13.1-py3-none-any.whl",
  "./wheels/pythonnet-3.0.5-py3-none-any.whl",
  "./wheels/networkx-3.4.2-py3-none-any.whl",
  "./wheels/scipy-1.16.0-cp311-cp311-win_amd64.whl",
  "./wheels/pillow-11.3.0-cp311-cp311-win_amd64.whl",
  "./wheels/py360convert-1.0.4-py3-none-any.whl"
]

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/"
]